FROM node:12.8.0

# コンテナ上の作業ディレクトリ作成
WORKDIR /app

# 後で確認出来るようにpackage.jsonを作成
RUN npm init -y

RUN yarn add ajv
RUN yarn add ajv-keywords
RUN yarn add file-saver
RUN yarn add js-yaml
RUN yarn add jszip
RUN yarn add moment
RUN yarn add skyway-js
RUN yarn add vue
RUN yarn add vue-class-component
RUN yarn add vue-mixin-decorator
RUN yarn add vue-property-decorator
RUN yarn add vue-router
RUN yarn add vue-slider-component
RUN yarn add vuedraggable
RUN yarn add vuex
RUN yarn add vuex-class
RUN yarn add crypto-js
RUN yarn add file-saver
RUN yarn add mathjs
RUN yarn add mustache


RUN yarn add --dev typescript
RUN yarn add --dev compression-webpack-plugin
RUN yarn add --dev json-loader
RUN yarn add --dev yaml-loader


RUN yarn add --dev @vue/cli-plugin-babel
RUN yarn add --dev @vue/cli-plugin-eslint
RUN yarn add --dev @vue/cli-plugin-typescript
RUN yarn add --dev @vue/cli-service
RUN yarn add --dev @vue/eslint-config-prettier
RUN yarn add --dev @vue/eslint-config-typescript
RUN yarn add --dev babel-eslint
RUN yarn add --dev eslint
RUN yarn add --dev eslint-plugin-vue
RUN yarn add --dev lint-staged
RUN yarn add --dev node-sass
RUN yarn add --dev sass-loader
RUN yarn add --dev vue-template-compiler
# RUN yarn add --dev @typescript-eslint/parser
RUN yarn add --dev typescript-eslint-parser
RUN yarn add --dev @types/mathjs
RUN yarn add --dev compression-webpack-plugin
RUN yarn add --dev json-loader
RUN yarn add --dev yaml-loader
RUN yarn add --dev @types/crypto-js
RUN yarn add --dev @types/mustache
RUN yarn add --dev eslint-plugin-prettier


